name       : network-manager
version    : 1.10.0
release    : 27
source     :
    - https://download.gnome.org/sources/NetworkManager/1.10/NetworkManager-1.10.0.tar.xz : 8abbd60cf0e56003a7b9428ceb50a58c80e02e045ac31c3399e9227a712e04de
license    :
    - LGPL-3.0
component  : network.base
summary    : Simple networking
description: |
    NetworkManager is a set of co-operative tools that make networking simple and straightforward. Whether WiFi, wired, 3G, or Bluetooth, NetworkManager allows you to quickly move from one network to another: once a network has been configured and joined once, it can be detected and re-joined automatically the next time it's available.
builddeps  :
    - pkgconfig32(dbus-1)
    - pkgconfig32(dbus-glib-1)
    - pkgconfig32(gio-2.0)
    - pkgconfig32(nss)
    - pkgconfig32(jansson)
    - pkgconfig32(libcurl)
    - pkgconfig32(liblzma)
    - pkgconfig32(libndp)
    - pkgconfig32(libnl-3.0)
    - pkgconfig(mm-glib)
    - dhclient
    - libgcrypt-32bit-devel
    - ncurses-32bit-devel
    - python-gobject-devel
    - readline-32bit-devel
    - vala
rundeps    :
    - dhclient
emul32     : yes
setup      : |
    unset LD_AS_NEEDED
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        normOpts="--without-modem-manager-1 --with-nmtui=no --enable-polkit=disabled --disable-polkit-agent"
    else
        normOpts="--with-modem-manager-1"
    fi
    %configure --with-systemdsystemunitdir=%libdir%/systemd/system \
                --with-session-tracking=systemd \
                --enable-vala \
                --disable-ppp \
                --with-dhclient=/usr/bin/dhclient \
                --enable-modify-system \
                --with-dist-version="Solus" \
                --with-suspend-resume=systemd \
                --with-udev-dir=/usr/lib/udev \
                --prefix=/usr \
                $normOpts
build      : |
    unset LD_AS_NEEDED
    %make
install    : |
    unset LD_AS_NEEDED
    %make_install
    ln -sv %libdir%/systemd/system/NetworkManager.service  $installdir/%libdir%/systemd/system/dbus-org.freedesktop.NetworkManager.service
    echo -e "[main]\nplugins=keyfile\n" > $installdir/etc/NetworkManager/NetworkManager.conf