name       : network-manager
version    : 1.32.4
release    : 68
source     :
    - https://download.gnome.org/sources/NetworkManager/1.32/NetworkManager-1.32.4.tar.xz : 29acbd41c78b7ef87ff88fec5360d1eaf8b5b6fcb90555d7391abc5e36923158
license    : GPL-2.0-or-later
component  :
    - network.base
    - livecd : network.base
summary    :
    - Simple networking
    - livecd : Live ISO configuration
description: |
    NetworkManager is a set of co-operative tools that make networking simple and straightforward. Whether WiFi, wired, 3G, or Bluetooth, NetworkManager allows you to quickly move from one network to another: once a network has been configured and joined once, it can be detected and re-joined automatically the next time it's available.
builddeps  :
    - pkgconfig32(dbus-glib-1)
    - pkgconfig32(gio-2.0)
    - pkgconfig32(gudev-1.0)
    - pkgconfig32(jansson)
    - pkgconfig32(libcurl)
    - pkgconfig32(liblzma)
    - pkgconfig32(libndp)
    - pkgconfig32(libnl-3.0)
    - pkgconfig32(nss)
    - pkgconfig32(uuid)
    - pkgconfig(mm-glib)
    - dhclient
    - libgcrypt-32bit-devel
    - ncurses-32bit-devel
    - ppp-devel
    - python-gobject-devel
    - readline-32bit-devel
    - vala
rundeps    :
    - dhclient
    - dnsmasq
    - ppp
    - usb-modeswitch
    - wireless-tools
    - wpa_supplicant
patterns   :
    - livecd :
        - /usr/lib/NetworkManager/conf.d/60-live-disable-hostname-mode.conf
emul32     : yes
environment: |
    unset LD_AS_NEEDED
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        normOpts="--without-modem-manager-1 --with-nmtui=no --enable-polkit=disabled --disable-gtk-doc --disable-introspection --disable-ppp"
    else
        normOpts="--with-modem-manager-1 --enable-ppp --enable-vala --with-pppd-plugin-dir=%libdir%/pppd/2.4.8/"
    fi
    %configure \
        --enable-modify-system \
        --with-config-dhcp-default=dhclient \
        --with-dbus-sys-dir=/usr/share/dbus-1/system.d \
        --with-dhclient=/usr/bin/dhclient \
        --with-dist-version="${version}-solus" \
        --with-session-tracking=systemd \
        --with-suspend-resume=systemd \
        --with-systemdsystemunitdir=%libdir%/systemd/system \
        --with-udev-dir=/usr/lib/udev \
        $normOpts
build      : |
    %make
install    : |
    %make_install
    ln -sv %libdir%/systemd/system/NetworkManager.service  $installdir/%libdir%/systemd/system/dbus-org.freedesktop.NetworkManager.service
    install -Dm00644 $pkgfiles/NetworkManager.conf $installdir/usr/lib/NetworkManager/conf.d/NetworkManager.conf
    install -Dm00644 $pkgfiles/20-connectivity-solus.conf $installdir/usr/lib/NetworkManager/conf.d/20-connectivity-solus.conf
    install -Dm00644 $pkgfiles/60-live-disable-hostname-mode.conf $installdir/usr/lib/NetworkManager/conf.d/60-live-disable-hostname-mode.conf
    if [[ -z "${EMUL32BUILD}" ]] ; then
        install -D -m 00644 $pkgfiles/NetworkManager.tmpfiles $installdir/%libdir%/tmpfiles.d/NetworkManager.conf
    fi
