name        : network-manager
version     : 0.9.8.6
release     : 11
source      :
    - http://ftp.gnome.org/pub/gnome/sources/NetworkManager/0.9/NetworkManager-0.9.8.6.tar.xz : 2289800de66fd7f8c141e029923beb39f43952e442b3cb864e3bf73b26c0c369
license     :
    - LGPLv3+
summary     : Simple networking
builddeps   :
    - pkgconfig(libnl-3.0)
    - pkgconfig(nss)
    - pkgconfig(mm-glib)
    - pkgconfig(xtables)
    - pkgconfig(libsoup-2.4)
    - vala
    - dhcpcd
description : |
    NetworkManager is a set of co-operative tools that make networking simple and straightforward. Whether WiFi, wired, 3G, or Bluetooth, NetworkManager allows you to quickly move from one network to another: once a network has been configured and joined once, it can be detected and re-joined automatically the next time it's available.
setup      : |
    %configure --disable-static \
                --with-systemdsystemunitdir=%libdir%/systemd/system \
                --with-session-tracking=systemd \
                --enable-vala \
                --disable-static \
                --disable-ppp
    find . -name "Makefile" | xargs sed -i 's@ -Werror@@g'

build      : |
    %make
install    : |
    %make_install
    ln -sv %libdir%/systemd/system/NetworkManager.service  $installdir/%libdir%/systemd/system/dbus-org.freedesktop.NetworkManager.service
