name       : network-manager
version    : 1.0.2
release    : 22
source     :
    - http://ftp.gnome.org/pub/gnome/sources/NetworkManager/1.0/NetworkManager-1.0.2.tar.xz : 359385707494bedbb48cfe0992ccfbcc4ac147dae1f7a47055c71e96439508ff
license    :
    - LGPL-3.0
summary    : Simple networking
builddeps  :
    - pkgconfig(libnl-3.0)
    - pkgconfig32(libnl-3.0)
    - pkgconfig(nss)
    - pkgconfig32(nss)
    - pkgconfig(mm-glib)
    - pkgconfig(xtables)
    - pkgconfig32(xtables)
    - pkgconfig(libsoup-2.4)
    - pkgconfig32(libsoup-2.4)
    - pkgconfig(libndp)
    - pkgconfig32(libndp)
    - pkgconfig32(uuid)
    - pkgconfig32(gudev-1.0)
    - pkgconfig32(dbus-glib-1)
    - vala
    - dhclient
    - glibc-32bit-devel
    - libgcc-32bit
    - readline-32bit-devel
    - ncurses-32bit-devel
    - dbus-32bit-devel
    - dbus-32bit
    - libgcrypt-32bit-devel
rundeps    :
    - dhclient
emul32     : yes
description: |
    NetworkManager is a set of co-operative tools that make networking simple and straightforward. Whether WiFi, wired, 3G, or Bluetooth, NetworkManager allows you to quickly move from one network to another: once a network has been configured and joined once, it can be detected and re-joined automatically the next time it's available.
setup      : |
    # Stop hostname changes, taken from arch linux
    %patch -p1 < $pkgfiles/no-set-hostname.patch
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        normOpts="--without-modem-manager-1 --with-nmtui=no --enable-polkit=disabled --disable-polkit-agent"
    else
        normOpts="--with-modem-manager-1"
    fi
    %configure --disable-static \
                --with-systemdsystemunitdir=%libdir%/systemd/system \
                --with-session-tracking=systemd \
                --enable-vala \
                --disable-static \
                --disable-ppp \
                --with-dhclient=/usr/bin/dhclient \
                --enable-modify-system \
                --with-dist-version="Solus" \
                --with-suspend-resume=systemd \
                --with-udev-dir=/usr/lib/udev \
                --prefix=/usr \
                $normOpts

    find . -name "Makefile" | xargs sed -i 's@ -Werror@@g'

build      : |
    %make
install    : |
    %make_install
    ln -sv %libdir%/systemd/system/NetworkManager.service  $installdir/%libdir%/systemd/system/dbus-org.freedesktop.NetworkManager.service
    echo -e "[main]\nplugins=keyfile\n" > $installdir/etc/NetworkManager/NetworkManager.conf
