name        : network-manager
version     : 1.0.2
release     : 18
source     :
    - http://ftp.gnome.org/pub/gnome/sources/NetworkManager/1.0/NetworkManager-1.0.2.tar.xz : 359385707494bedbb48cfe0992ccfbcc4ac147dae1f7a47055c71e96439508ff
license     :
    - LGPL-3.0
summary     : Simple networking
builddeps   :
    - pkgconfig(libnl-3.0)
    - pkgconfig(nss)
    - pkgconfig(mm-glib)
    - pkgconfig(xtables)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libndp)
    - vala
    - dhclient
rundeps     :
    - dhclient
description : |
    NetworkManager is a set of co-operative tools that make networking simple and straightforward. Whether WiFi, wired, 3G, or Bluetooth, NetworkManager allows you to quickly move from one network to another: once a network has been configured and joined once, it can be detected and re-joined automatically the next time it's available.
setup      : |
    # Stop hostname changes, taken from arch linux
    %patch -p1 < $pkgfiles/no-set-hostname.patch
    %configure --disable-static \
                --with-systemdsystemunitdir=%libdir%/systemd/system \
                --with-session-tracking=systemd \
                --enable-vala \
                --disable-static \
                --disable-ppp \
                --with-modem-manager-1 \
                --with-dhclient=/usr/bin/dhclient \
                --enable-modify-system \
                --with-dist-version="Solus"
    
    find . -name "Makefile" | xargs sed -i 's@ -Werror@@g'

build      : |
    %make
install    : |
    %make_install
    ln -sv %libdir%/systemd/system/NetworkManager.service  $installdir/%libdir%/systemd/system/dbus-org.freedesktop.NetworkManager.service
    echo -e "[main]\nplugins=keyfile\n" > $installdir/etc/NetworkManager/NetworkManager.conf
