name       : network-manager
version    : 1.10.10
release    : 42
source     :
    - https://download.gnome.org/sources/NetworkManager/1.10/NetworkManager-1.10.10.tar.xz : 244e29c0d1a57492df9aaf2d8c31e4a1b76bdfa8e862ae106239862e1c78c3ca
license    : GPL-2.0-or-later
component  : network.base
summary    : Simple networking
description: |
    NetworkManager is a set of co-operative tools that make networking simple and straightforward. Whether WiFi, wired, 3G, or Bluetooth, NetworkManager allows you to quickly move from one network to another: once a network has been configured and joined once, it can be detected and re-joined automatically the next time it's available.
builddeps  :
    - pkgconfig32(dbus-1)
    - pkgconfig32(dbus-glib-1)
    - pkgconfig32(gio-2.0)
    - pkgconfig32(nss)
    - pkgconfig32(jansson)
    - pkgconfig32(libcurl)
    - pkgconfig32(liblzma)
    - pkgconfig32(libndp)
    - pkgconfig32(libnl-3.0)
    - pkgconfig32(gudev-1.0)
    - pkgconfig(mm-glib)
    - pkgconfig32(uuid)
    - dhclient
    - libgcrypt-32bit-devel
    - ncurses-32bit-devel
    - ppp-devel
    - python-gobject-devel
    - readline-32bit-devel
    - vala
rundeps    :
    - dhclient
    - dnsmasq
    - usb-modeswitch
    - wireless-tools
    - wpa_supplicant
emul32     : yes
setup      : |
    unset LD_AS_NEEDED
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        normOpts="--without-modem-manager-1 --with-nmtui=no --enable-polkit=disabled --disable-polkit-agent --disable-ppp"
    else
        normOpts="--with-modem-manager-1 --enable-ppp"
    fi
    %apply_patches
    %configure --with-systemdsystemunitdir=%libdir%/systemd/system \
                --with-session-tracking=systemd \
                --enable-vala \
                --with-dhclient=/usr/bin/dhclient \
                --enable-modify-system \
                --with-dist-version="${version}-solus" \
                --with-suspend-resume=systemd \
                --with-udev-dir=/usr/lib/udev \
                --prefix=/usr \
                $normOpts
build      : |
    unset LD_AS_NEEDED
    %make
install    : |
    unset LD_AS_NEEDED
    %make_install
    ln -sv %libdir%/systemd/system/NetworkManager.service  $installdir/%libdir%/systemd/system/dbus-org.freedesktop.NetworkManager.service
    install -m 00644 $pkgfiles/NetworkManager.conf $installdir/etc/NetworkManager/NetworkManager.conf
    install -m 00644 $pkgfiles/20-connectivity-solus.conf $installdir/etc/NetworkManager/conf.d/20-connectivity-solus.conf
    if [[ -z "${EMUL32BUILD}" ]] ; then
        install -D -m 00644 $pkgfiles/NetworkManager.tmpfiles $installdir/%libdir%/tmpfiles.d/NetworkManager.conf
    fi
